name: easy_tree
description: Build a simple tree of a specific node in a complex Widget tree.
version: 0.0.1+1
homepage: https://github.com/yiiim/easy_tree

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
